title:        Ishan
tagline:      'Hyde, By Ishan'
description:  'Sample Blog for Alan.. An open source and mobile first theme for <a href="http://jekyllrb.com" target="_blank">Jekyll</a>. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:          http://hydesample.wuxxa.com 
version:      1.1.1
author:
  name:       ''
  email:      ''
#markdown:     rdiscount
permalink:    pretty
pygments:     true
paginate:     5
